// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Surveymatic.Data;

namespace Surveymatic.Migrations
{
    [DbContext(typeof(HelpContext))]
    [Migration("20210519162328_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("Surveymatic.Data.Help", b =>
                {
                    b.Property<int>("HelpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("HelpTag")
                        .HasColumnType("longtext");

                    b.HasKey("HelpId");

                    b.ToTable("Help");
                });

            modelBuilder.Entity("Surveymatic.Data.HelpEntry", b =>
                {
                    b.Property<int>("HelpEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<int?>("HelpId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("longtext");

                    b.HasKey("HelpEntryId");

                    b.HasIndex("HelpId");

                    b.ToTable("HelpEntry");
                });

            modelBuilder.Entity("Surveymatic.Data.HelpEntry", b =>
                {
                    b.HasOne("Surveymatic.Data.Help", "Help")
                        .WithMany("Entries")
                        .HasForeignKey("HelpId");

                    b.Navigation("Help");
                });

            modelBuilder.Entity("Surveymatic.Data.Help", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
